

language: objective-c
osx_image: xcode10.2
xcode_sdk: iphonesimulator12.0
script:
- cd Source
- set -o pipefail
- travis_retry xcodebuild clean build -workspace source.xcworkspace -scheme source -destination "platform=iOS Simulator,name=iPhone 6" CODE_SIGN_IDENTITY=
